### ISSUE TITLE
Upgrade canvas version

### ISSUE THREAD

**Issue by joevp** [nathan-muir/canvgc#2]
Node-canvas has fixed the include path for cairo in more recent version. The currently pinned version of canvas will not work with cairo.

**Comment by dancingfrog** [comment]
I guess there's a reason why canvg is stuck in the src directory rather than being listed as an npm dependency in package.json, but I have no idea what that reason is...

**Comment by dancingfrog** [comment]
My first guess is that the canvg.js file in this repo is actually a completely different file than https://github.com/gabelerner/canvg/blob/master/canvg.js

I this correct?

**Comment by nathan-muir** [comment]
Well, when this was built, `canvg` wasn't even in npm / github. So that was the first reason it was included locally.

The actual version used is - https://github.com/yetzt/node-canvg

While possible, it might take a bit of work to get it working with the current version.
